---
title: "Visualisation"
author: "Guillaume Slizewicz"
date: "22 August 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#######LIBRARIES
library(plotly)
library("ggmap")# getting maps and coordinates from google
library(maptools)# getting maps and coordinates from google
library(maps)# getting maps and coordinates from google
library("ggplot2")# plotting the data
library(dplyr)#tidying dataset
library(rworldmap)
library(stringr)#dealing with strings and replacing strings in observations
library(RCurl)

#####MAIN FILE
df.viz<- read.csv("https://raw.githubusercontent.com/basgpol/SDS-group12/master/Exam_project/transferdata.final.csv", encoding = "UTF8", header = TRUE)

df.viz<- filter(df.viz,transfer.fee>0)


#######TRANSFER PATH
transfer.path.full = read.csv("https://raw.githubusercontent.com/basgpol/SDS-group12/master/Exam_project/transfer_path_full.csv", header=TRUE, stringsAsFactors=TRUE, fileEncoding="UTF8") # loading saved version of uncleaned player data

myLocation <- "Zurich"
myMap <- get_map(location= myLocation,
                 source="stamen", maptype="watercolor", crop=FALSE,zoom=4)

gg<-ggmap(myMap)+#calling map
  geom_path(aes(x = lon, y = lat, group = factor(name)), #putting paths on the map
            colour="red", data = transfer.path.full, alpha=0.3)

#######EUROPEAN MAP OF CLUBS
df.spending.club<-read.csv("https://raw.githubusercontent.com/basgpol/SDS-group12/master/Exam_project/df_spending_club_with_geo.csv", encoding = "UTF8", header = TRUE)

mapclubs <- ggmap(myMap) +
     geom_point(aes(x = lon, y = lat, size=transfer.fee.total), data =df.spending.club,col="red", alpha=0.4)+
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks= element_line(color=NA),
        axis.line = element_line(color = NA))
mapclubs
#with plotly

# m <- list(
#   colorbar = list(title = "Total transfer spending"),
#   size = 10, opacity = 0.8, symbol = 'circle'
# )
# 
# g <- list(
#   scope = 'europe',
#   projection = list(type = 'mercator'),
#   showland = TRUE,
#   landcolor = toRGB("gray95"),
#   subunitcolor = toRGB("gray85"),
#   countrycolor = toRGB("gray85"),
#   countrywidth = 0.5,
#   subunitwidth = 0.5
# )

#######AGE

p.age = ggplot(df.viz, aes(x = transferage , y = transfer.fee))
p.age<-p.age + geom_point(stat = "identity")+
          #geom_point(aes(text = paste("Name:",name))+
          geom_smooth(aes(colour = transferage, fill = transferage))+
          ggtitle("Age repartition of transfers in European leagues")
#plotly.p.age<-ggplotly(p.age)

#####TIME LEFT
p.time <- ggplot(data=df.viz, aes(x = contract.left.month , y = transfer.fee)) +
  geom_point(stat = "identity")+
  #geom_point(aes(text = paste(name, " to ", club.to)), size = 4) +
  geom_smooth(aes(colour = contract.left.month, fill = contract.left.month))+
  ggtitle("Time left on contract seems to be positively correlated with transfer fees")

#plotly.p.time <- ggplotly(p.time)

###AVERAGE SPENDING BY LEAGUE

#finding mean for every league
df.viz.ave<-df.viz %>% 
  group_by(league) %>% 
  dplyr::summarise(
    sum.transfer=sum(transfer.fee))

df.viz.ave<-df.viz.ave %>% 
  mutate(number.of.clubs = ifelse(league=="Bundesliga",18,20)) %>% 
  mutate(average.spending=sum.transfer/number.of.clubs)
#ordering
df.viz.ave <- transform(df.viz.ave, 
                        league = reorder(league, average.spending))
#plotting it
p.spend = ggplot(df.viz.ave, aes( x =league, y=average.spending, fill=league))
p.spend<-p.spend + geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x =element_blank(),
        panel.grid.major.y = element_line(colour="#CACACA", size=0.2), #add grid
        axis.ticks= element_line(color=NA),
        panel.grid.major.x = element_blank(),
        axis.title.y =element_text(size  = 7,
                                  angle = 90,
                                  hjust = -3,
                                  vjust = 1),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        text=element_text(family="Computer Modern"))+
  ggtitle("Premier League Clubs spend far more on average than any other leagues' clubs")+
  scale_fill_manual("National leagues",
                    values=c( "#BF9692", "#FFAA00", "#3B8686", "#1f3057","#779C00", "#DEE3DC"))
#####CLUB STATUS
df.viz.status<-df.viz %>% 
  group_by(Status) %>% 
  dplyr::summarise(mean.transfer=mean(transfer.fee))

#Ordering
df.viz.status <- transform(df.viz.status, 
                                  Status = reorder(Status, mean.transfer))
#plotting
p.club = ggplot(df.viz.status, aes(y= mean.transfer, x = Status, fill=Status))
p.club<- p.club + geom_bar(stat = "identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x =element_text(size  = 7),
        axis.ticks= element_line(color=NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(colour="#CACACA", size=0.2), #add grid
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.text=element_blank(),
        axis.title.y=element_blank(),
        legend.title=element_blank(),
        legend.position="none",
        text=element_text(family="Computer Modern"))+
  ggtitle("Top Club spend far more on average than other leagues' clubs")+
  scale_fill_manual(values=c( "#CFF09E", "#A8DBA8", "#79BD9A", "#3B8686"))


```

## Visualisation

Some examples of visualisations

```{r cars}
#including Summary

```



```{r pressure, echo=FALSE}


mapclubs

gg




p.age



p.spend

p.club

```

